{% set name = "lhapdf" %}
{% set version = "6.5.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/hepcedar/lhapdf/-/archive/lhapdf-{{ version }}/lhapdf-lhapdf-{{ version }}.tar.gz
  sha256: 165143a5487d845d22e2d4dbe4ab4f51f09571756e80f71e3eacd7d412efb5d8
  patches:
    # Apply patch to wrappers/python/build.py.in to build bindings with Cython
    # https://gitlab.com/hepcedar/lhapdf/-/blob/c5b048f5794e483d85801d1ae39f42aaa46999dd/wrappers/python/build.py.in
    - osx_patch.diff  # [osx]

build:
  skip: true  # [win]
  skip: true  # [python_impl == "pypy"]
  number: 0
  run_exports:
    - {{ pin_subpackage("lhapdf", max_pin="x.x") }}
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.24  # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - automake
    - autoconf
    - libtool
    - wget
  host:
    - python
    - cython >=0.24
  run:
    - python

test:
  requires:
    - cxx-compiler
    - numpy
  source_files:
    - examples
  imports:
    - lhapdf

about:
  home: https://lhapdf.hepforge.org/
  summary: 'LHAPDF is a general purpose C++ interpolator, used for evaluating PDFs from discretised data files. '
  description: |
    LHAPDF is a library implementing a standard to represent Parton
    Distribution Functions (PDFs) which is ubiquitous in the field of High Energy
    Physics. PDFs, which describe the structure of the proton, are an essential
    ingredient for experimental and phenomenological studies at the Large Hadron
    Collider (LHC). LHAPDF allows PDF fitting collaborations to distribute their
    results in a format that is interoperable with tools requiring PDFs as input,
    such as Monte Carlo Event generations. The LHAPDF project maintains a remote
    repository of PDFs, which can be installed with tools that accompany the
    library.
    Please make sure to cite the following paper if you use LHAPDF6
    "LHAPDF6: parton density access in the LHC precision era" Eur.Phys.J. C75
    (2015) 3, 132
    http://arxiv.org/abs/1412.7420
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING
  doc_url: https://lhapdf.hepforge.org
  dev_url: https://gitlab.com/hepcedar/lhapdf

extra:
  recipe-maintainers:
    - conda-forge/hepmc3
    - scarlehoff
    - Zaharid
